version: '3'

volumes:
  queue:
    labels:
      com.screaming_bunny.container: 'RabbitMQ'
      com.screaming_bunny.description: 'Persistent RabbitMQ Volume'

services:
  transport-mqtt:
    hostname: transport-mqtt
    image: g2inc/oif-device-transport-mqtt
    build:
      context: ./device/transport/mqtt
    working_dir: /opt/transport/MQTT
    env_file:
      - ./environment/queue.connect.env
      - ./environment/mqtt_transport.env
    external_links:
      - queue
    depends_on:
      - queue
    entrypoint:
      - sh
      - dev_start.sh

  transport-https:
    hostname: transport-https
    image:  g2inc/oif-device-transport-https
    build:
      context: ./device/transport/https
    working_dir: /opt/transport
    env_file:
      - ./environment/queue.connect.env
    external_links:
      - queue
    ports:
      - 5001:5001
    depends_on:
      - queue
    entrypoint:
      - sh
      - dev_start.sh

  transport-coap:
    hostname: transport-coap
    image:  g2inc/oif-device-transport-coap
    build:
      context: ./device/transport/coap
      dockerfile: Dockerfile
    working_dir: /opt/transport/COAP
    env_file:
      - ./environment/queue.connect.env
    external_links:
      - queue
    ports:
      - '5682:5682/udp'
    depends_on:
      - queue
    entrypoint:
      - sh
      - dev_start.sh

  queue:
    hostname: rabbit
    image: rabbitmq:management-alpine
    ports:
      - '1883:1883'
      - '15673:15672'
    command: sh -c "rabbitmq-plugins enable rabbitmq_mqtt; docker-entrypoint.sh rabbitmq-server"
    volumes:
      - queue:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:15672']
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure:5

  actuator-isr:
    hostname: actuator-isr
    image:  g2inc/oif-device-actutator-isr
    build:
      context: ./device/actuator/ISR
    env_file:
    - ./environment/queue.connect.env
    environment:
      QUEUE_EXCHANGE: 'actuator'
    external_links:
      - queue
    depends_on:
      - queue
    entrypoint:
      - sh
      - start.sh
    restart: on-failure:5

  actuator-isr:                                   # container name
    hostname: universal-actuator                      # hostname of container
    image: gcr.io/openc2home/universal-actuator                   # image name
    build:
      context: ./device/actuator/universal-actuator                    # location of Dockerfile
    env_file:
    - ./environment/queue.connect.env           # path to shared environment variables
    environment:
      QUEUE_EXCHANGE: 'actuator'                # actuator specific environment variable (this can stay the same for your container)
    external_links:
      - queue                                   # link to internal buffer (more on this below)
    depends_on:
      - queue                                   # indicates that this container should wait for queue to exist before running
    entrypoint:                                 # indicates script to run upon container startup
      - sh
      - start.sh
    restart: on-failure:5 
